### ISSUE TITLE
AttributeError: module 'trimap' has no attribute 'transform'

### ISSUE THREAD

**Issue by owlisie** [eamid/examples#2]
Good Morning. I tried the example code in Window, using Pycharm, anaconda virt env of python=3.8, cuda=11.3.1, with PyTorch.
First, in your code, trimap called the function name 'trasform()' to clustering while others uses fit_transform.
When I run the code, AttributeError: module 'trimap' has no attribute 'transform' has alarmed.
I edited this line into trimap.TRIMAP().fit_transform(key, examples) but then the error said that key = random.PRNGKey(123) should be in 2-dimensional but only returns 1-dimensional so the 'n, dim = X.shape()' could be operated properly.
I searched for the jax.random.PRNGKey() but all the examples uses it in additional step to make actual random number.
I installed jax and jaxlib in pip in anaconda, jax with sourcecode and jaxlib with wheel.
If there's any advice to offer, thanks in advance.

**Comment by eamid** [comment]
Hi,

If I understand correctly, you are trying to use the JAX implementation of TriMap: https://github.com/google-research/google-research/tree/master/trimap  

Please make sure you are importing the right package (it might be that you also have the Python + Numba version installed). Maybe try running this example first:  

```
import jax.random as random
from sklearn.datasets import load_digits
import trimap

digits = load_digits()
key = random.PRNGKey(42)

embedding = trimap.transform(key, digits.data, distance='euclidean')
```

**Comment by owlisie** [comment]
Thanks for your consideration.
I've installed required packages like:
annoy  1.17.1
jax  0.3.16
jaxlib  0.3.14
numba  0.55.1
numpy  1.21.5
scikit-learn  1.1.1

And I tried the code that you sent but it didn't work returning
AttributeError : module 'trimap' has no attribute 'transform'. I installed
trimap with download your git from : https://github.com/eamid/trimap, and
run the setup.py.

Could it be the problem of trimap that I installed with setup.py?

Sincerely,
Young In Jang

2022년 8월 12일 (금) 오후 2:20, Ehsan Amid ***@***.***>님이 작성:

**Comment by eamid** [comment]
For the Python + Numba version, you should do:

```
import trimap
from sklearn.datasets import load_digits

digits = load_digits()

embedding = trimap.TRIMAP().fit_transform(digits.data)
```

**Comment by owlisie** [comment]
Sorry for the late reply.

The project worked perfectly after modifying the fit_transform as you
suggested.
I appreciate for the advice.

2022년 8월 13일 (토) 오전 3:32, Ehsan Amid ***@***.***>님이 작성:

**Comment by eamid** [comment]
Thanks, glad it worked!
